export const FETCH_GENRES = "FETCH_GENRES";

export const FETCH_GENRES_ARTIST = "FETCH_GENRES_ARTIST";

export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
